### ISSUE TITLE
PHPStan 0.10 incompatibility

### ISSUE THREAD

**Issue by enumag** [eloquent/phpstan-phony#5]
```
Internal error: Argument 1 passed to Eloquent\Phpstan\Phony\Type\MockReturnType::getTypeFromCall() must implement interface PHPStan\Reflection\ParametersAcceptor, instance of  
PHPStan\Reflection\Php\PhpMethodReflection given, called in .../vendor/eloquent/phpstan-phony/src/Type/MockReturnType.php on line 63    
```

**Comment by ezzatron** [comment]
Okay, so here's what's happening.

Changing the `composer.json` constraint for PHPStan to `^0.9||^0.10` doesn't magically cause the tests to be run under both PHPStan `0.9.x` and `0.10.x`. In fact, the [platform](https://github.com/eloquent/phpstan-phony/blob/9b10cba/composer.json#L40) configuration makes sure that only dependencies that are compatible with the specified version of PHP are installed. Since PHPStan `0.10.x` drops support for PHP `7.0.x`, this means that Composer would never choose PHPStan `0.10.x`, and the tests were always running against PHPStan `0.9.x`.

In retrospect, I should have known that simply bumping the PHPStan version in `composer.json` was too good to be true. As it turns out, there's a [bunch of BC breaks](https://github.com/phpstan/phpstan/releases/tag/0.10) in PHPStan `0.10.x` for extensions. Given that fact, I'm not keen to attempt to support PHPStan `0.9.x` and `0.10.x` in the same release of `phpstan-phony`. I've created #6 to address the actual changes required to support `0.10.x`, and pulled the `0.2.0` version of `phpstan-phony` from Packagist.

The changes seem to be working fine, and the tests pass. Im going to merge them to master with a branch alias for `3.x` and I'd appreciate if you could take the time to give it a quick real-world test before I go through the release process again.

**Comment by enumag** [comment]
Yeah I didn't really expect a full compatibility so I was surprised when you released 0.2 right a way. I'm going to test the WIP version now.

**Comment by ezzatron** [comment]
@enumag Is PHPStan `0.10.x` support working for you now?

**Comment by enumag** [comment]
@ezzatron Yeah. I've just finished updating my project and everything seems alright. No Phony-related problems. 👍

**Comment by ezzatron** [comment]
Thanks. I just tagged [0.3.0](https://github.com/eloquent/phpstan-phony/releases/0.3.0), let me know if you encounter any more issues.
